name: HANGMAN-GAME - DEFAULT

on:
  schedule:
    - cron: '1 1 1 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - main

env:

  APPLICATION_VERSION: 0.1.0
  APPLICATION_NAME: cy-action-clean

permissions: write-all

jobs:

 sonarcloud-analyse:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      if: ${{ github.event_name == 'schedule' }}
      uses: github/codeql-action/init@v2
      with:
        languages: javascript

    - name: Install dependencies
      run: npm install

    - name: Prettier format
      if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
      run: npm run prettier --config ./.prettierrc

    - name: Save  changes
      if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
      working-directory: ${{github.workspace}}
      run: |
        git stash
        git checkout ${{github.head_ref}}
        git stash pop
        git config user.name "MGuillaumeF"
        git config user.email "${{secrets.EMAIL}}"
        git add .
        (git commit -m "[AUTO] prettier format write" && git push) || echo 'No modification to save'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Perform CodeQL Analysis
      if: ${{ github.event_name == 'schedule' }}
      uses: github/codeql-action/analyze@v2

    - name: tests
      run: npm run cy:run

    - name: ESlint analyze json
      run: npm run lint:eslint:json || echo FAILED

    - name: ESlint analyze html
      run: npm run lint:eslint || echo FAILED

    - name: Copy reports
      if: always()
      run: |
        tree cypress
        mkdir -p ./dist/cypress-reports
        cp -R ./cypress/reports ./dist/cypress-reports

    - name: Audit dependencies
      working-directory: ${{github.workspace}}/client
      run: npm audit --json > ./dist/reports/audit-dependency-report.json || echo FAILED

    - name: Convert Audit dependencies client report
      run: ./node_modules/.bin/audiso --input-file=./dist/reports/audit-dependency-report.json --output-file ./dist/reports/audit-report.json

    - name: Archive Analyses reports
      uses: actions/upload-artifact@v3
      with:
        name: IHM-Hangman-Game-Analyses-report
        path: ${{github.workspace}}/dist

    - name: Setup sonarqube
      if: github.actor != 'dependabot[bot]'
      uses: warchant/setup-sonar-scanner@v4

    - name: Run SonarQube full
      working-directory: ${{github.workspace}}
      if: github.actor != 'dependabot[bot]'
      env:
        GITHUB_TOKEN: ${{ secrets.SONAR_REPO_ACCESS_TOKEN }}
      run: sonar-scanner
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        -Dsonar.verbose=false
        -Dsonar.branch.name=branch-full

    - name: Run SonarQube
      if: github.actor != 'dependabot[bot]'
      env:
        GITHUB_TOKEN: ${{ secrets.SONAR_REPO_ACCESS_TOKEN }}
      run: sonar-scanner
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
        -Dsonar.verbose=false
