name: CY-ACTION-CLEANER - DEFAULT

on:
  schedule:
    - cron: '1 1 1 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: 
      - main
permissions: write-all

jobs:

 sonarcloud-analyse:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      if: ${{ github.event_name == 'schedule' }}
      uses: github/codeql-action/init@v2
      with:
        languages: javascript

    - name: Install dependencies
      run: npm install

    - name: Prettier format
      if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
      run: npm run prettier --config ./.prettierrc

    - name: Save  changes
      if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
      run: |
        git stash
        git checkout ${{github.head_ref}}
        git stash pop
        git config user.name "MGuillaumeF"
        git config user.email "${{secrets.EMAIL}}"
        git add .
        (git commit -m "[AUTO] prettier format write" && git push) || echo 'No modification to save'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Perform CodeQL Analysis
      if: ${{ github.event_name == 'schedule' }}
      uses: github/codeql-action/analyze@v2

    - name: tests
      run: npm run cy:run
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: ESlint analyze json
      run: npm run lint:eslint:json || echo FAILED

    - name: ESlint analyze html
      run: npm run lint:eslint || echo FAILED

    - name: Audit dependencies
      run: npm audit --json > ./audit-dependency-report.json || echo FAILED

    - name: Convert Audit dependencies client report
      run: ./node_modules/.bin/audiso --input-file=./audit-dependency-report.json --output-file ./audit-report.json

    - name: Setup sonarqube
      if: github.actor != 'dependabot[bot]'
      uses: warchant/setup-sonar-scanner@v4

    - name: Run SonarQube full
      if: github.actor != 'dependabot[bot]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.verbose=false
        -Dsonar.branch.name=branch-full

    - name: Run SonarQube
      if: github.actor != 'dependabot[bot]'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
        -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.verbose=false

 dependabot:
    needs: [sonarcloud-analyse]
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:

      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.3.4
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Enable auto-merge for Dependabot PRs 
        run: gh pr merge --delete-branch --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
